# Generated by Django 5.1.3 on 2024-12-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='comments',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='likes',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
